### ISSUE TITLE
Image gallery thumbnail white in corner

### ISSUE THREAD

**Issue by jhung0** [CellProfiler/CellProfiler-Analyst#140]
Note that there's this white dot at the bottom right corner of the object images in classifier and image gallery. However, the fetched images don't seem to have it. Does it matter? Should we have it?

**Comment by dlogan** [comment]
IIRC, this dot was a workaround (ok, "hack") to get multiple channel images to all scale their RGB intensities equally.  Otherwise, an intensity normalization would affect each RGB channel independently and might cause huge normalization variations between thumbnails.

If there is a better fix, so be it!

**Comment by daviddao** [comment]
#141 turned out to be unrelated to this dot. Therefore, I wouldn't include it into the image gallery image thumbnails.
