### ISSUE TITLE
Color mapping of certain object features 

### ISSUE THREAD

**Issue by daviddao** [CellProfiler/CellProfiler-Analyst#159]
Proposal from @mrohban : Color mapping of CP features (i.e RNA intensity) directly on the cells in the image.

**Comment by AnneCarpenter** [comment]
In essence, the idea here is to recreate all the options in CellProfiler's module/data tool DisplayDataOnImage (it allows showing measurements as text, but also using a colormap on the objects). 

This is not a trivial feature to add to CellProfiler Analyst because it requires CPA have knowledge of the segmentation results, which is currently not the case (CPA typically only knows the XY location of the centroid of objects, and not the outlines resulting from segmentation).

Of course, showing/hiding outlines from segmentation would also be super useful in CPA, we just need to think about the best way to provide this information to CPA (perhaps providing paths to previously-saved label matrices or segmentation outlines is the best approach - calculating on the fly is likely not feasible).
