### ISSUE TITLE
Nightly build of CPA freezes loading a 1.3GB SQLite database

### ISSUE THREAD

**Issue by bfeng0** [CellProfiler/CellProfiler-Analyst#219]
Hi All-

I've encountered an issue using the nightly (July 26th? -not sure why there aren't builds since then) build of CPA to open an SQLite database that the release version of the program opens without problem.  I have clicked the dock icon as mentioned next to the download link.  

I'm not getting any obvious error messages, so it's a bit hard to know what additional information might be useful in troubleshooting this.  I've included the sql file with my schema.

[sqlite_scheme.zip](https://github.com/CellProfiler/CellProfiler-Analyst/files/409958/sqlite_scheme.zip)

I feel like the nightly build is generally slower than the release build at a lot of things, so I partially wonder if it's really taking a long time, but at this point I've waited up to 15 minutes and still nothing.  It opens using the release version of the code in <1min.

**Comment by jhung0** [comment]
And this happens every time you open it? Which os?

On Aug 10, 2016 05:59, "bfeng0" <notifications@github.com> wrote:

Hi All-

I've encountered an issue using the nightly (July 26th? -not sure why there
aren't builds since then) build of CPA to open an SQLite database that the
release version of the program opens without problem. I have clicked the
dock icon as mentioned next to the download link.

I'm not getting any obvious error messages, so it's a bit hard to know what
additional information might be useful in troubleshooting this. I've
included the sql file with my schema.

sqlite_scheme.zip
<https://github.com/CellProfiler/CellProfiler-Analyst/files/409958/sqlite_scheme.zip>

I feel like the nightly build is generally slower than the release build at
a lot of things, so I partially wonder if it's really taking a long time,
but at this point I've waited up to 15 minutes and still nothing. It opens
using the release version of the code in <1min.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CellProfiler/CellProfiler-Analyst/issues/219>, or mute
the thread

**Comment by bfeng0** [comment]
Mac OS

**Comment by bfeng0** [comment]
Update: tried again with the latest nightly build.  After 20 minutes, it loaded.  Is that kind of time expected on databases of this size?

**Comment by jhung0** [comment]
I don't think so because the example database is .5GB. Is that consistently
the time each time you start?

**Comment by bfeng0** [comment]
Yes, consistently.  And the release version of the software opens this database up in a few seconds.

**Comment by jhung0** [comment]
Good to know... did you change anything in the properties file from
CellProfiler?

**Comment by bfeng0** [comment]
No, same properties file.

**Comment by jhung0** [comment]
Sorry, I'll need more time to check properly, but can you try changing
check_tables?

**Comment by bfeng0** [comment]
Sorry for the delayed response, but indeed turning check_tables to "no" made loading this database much faster.

Are there any caveats I should be aware of with changing this setting?

Thanks!
-Brian

**Comment by jhung0** [comment]
It tells Classifier whether to check your tables at startup for anomalies
such as missing/None/NULL values and makes a new table if it finds that.
