### ISSUE TITLE
Unable to re-load saved classifier with stable/nightly

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#247]
Using both the stable and nightly builds, I'm unable to save and then re-load a classifier file (at least, created with RF).

CPA simply reports "Error loading classifier model". Since I don't what commit corresponds to the stable and (now-outdated) nightly builds, I can't provide a stack trace from the try/except. However, running from source seems to save/re-load just fine.

**Comment by kaischleicher** [comment]
Hi, I've just tested this again and the problem persist using CPA 2.2.1 and also with the 2.3 nightly (tested on windows). See [crosspost at the CP forum](http://forum.cellprofiler.org/t/error-loading-classifier-model/3740/5?u=cellkai)

**Comment by jhung0** [comment]
What about from source?

**Comment by braymp** [comment]
Currently, I can't run from source since I run into the same enableLogging msg reported here: https://github.com/CellProfiler/python-bioformats/issues/89

**Comment by bethac07** [comment]
@mcquin is going to push a new release of python-bioformats RN that incorporates the enableLogging fix, because she is delightful.

**Comment by mcquin** [comment]
@braymp Can you give it a try with python-bioformats 1.3.2? https://pypi.python.org/pypi/python-bioformats

**Comment by jhung0** [comment]
I also ran into that issue when running from source but I pushed a change so it now works for me

**Comment by braymp** [comment]
@jhung0: Does @mcquin's PR obviate the need for the commit that you made?

**Comment by jhung0** [comment]
I think it should work. Is it working for you?

**Comment by braymp** [comment]
Just gave it a try with the stable build from the website; still yielded a error. I'm attaching the model file.
[my_model.zip](https://github.com/CellProfiler/CellProfiler-Analyst/files/1598153/my_model.zip)

**Comment by jhung0** [comment]
I'm not sure that the stable build has been updated since early 2017, so
you'd have to test it from source. I'll try to get builds back up after I'm
done with my current work.

**Comment by lorenzoascari** [comment]
Hi,

I tried to follow the instructions from this page here: https://github.com/CellProfiler/CellProfiler/wiki/Source-installation-(Windows), and from here: https://github.com/CellProfiler/CellProfiler-Analyst/wiki/Cellprofiler-analyst-developer’s-version-installation-for-pc, to install from source both CP and CPA.

I’m not an expert, so I had to follow some tips on stack overflow to set the environment variables for Java development kit and java runtime environment on my PC (I’m running on windows) otherwise I could not properly install some python packages. Moreover, I had to deal with some errors installing javabridge and python-bioformats created by Microsoft Visual Studio (e.g LINK : fatal error LNK1181: cannot open input file filename). In the end, I managed to run CPA from source and I was able to save a classifier.model using random forest for my classification. I also noticed some new features that are not available in the stable last stable version.

So happy? Not really, as from here on things became a bit messy…I was not able to install any CellProfiler version as there is no CellProfiler.py file in the new repository (version 3.0.1). I tried to use the old version 2.1.1 where the CellProfiler. py file is present but it did’t work, probably either because the old version is no more supported (the cmd shell failed to download some file required) or because I was not able to fix some errors mainly linked to the LINK settings in Visual Studio. Moreover, the new java environments variables that I had to set are not compatible with CP and CPA versions installed from the .exe files. So it came up that I could not use CPA installed from source and CP installed from an .exe file together. I rolled back to the stable versions of both programs (CP 2.2.0 and CPA 2.2.1) which work only if I erase the environments variables (JAVA_HOME) required to run CPA from source…

Is there a simple way to run CPA from source having CP installed from the stable .exe version (2.2.0 or 3.0)?
It could be really helpful if I could use the classifier model to train the system without having to build a new training set all the times…

I will update the GitHub issue in a minute…

thank you very much for your support and suggestions

**Comment by cbaer** [comment]
I'm also running into this issue - I can't run a saved Classifier model. 
I'm running CPA from source.  
Loading a model saved with RandomForest ends this way:
INFO:root:Classifier model succesfully loaded
INFO:root:Loaded trained classifier: RandomForestClassifier on classes:
INFO:root:A
INFO:root:G
INFO:root:M
INFO:root:P
INFO:root:T
INFO:root:negatives
INFO:root:CAUTION: Classifier needs to be trained on the current data set!

For comparison, loading a model saved with FGB gives this:
ERROR:root:Error loading classifier model
INFO:root:Error loading classifier model

Any suggestions?  Thanks!

**Comment by DavidStirling** [comment]
Should be fixed
