### ISSUE TITLE
Resize large images

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler-Analyst#51]
This one has a workaround, but is a major annoyance.  TL;DR = Large images need to be resized properly.
(Tested on Windows, but pretty sure it occurs on Mac too in some fashion)

If the image displayed (via-double-clicking a Classifier thumbnail) does not fit in the windowing desktop, then the image over-extends past the desktop.  
![screen shot 2014-07-07 at 7 25 57 pm](https://cloud.githubusercontent.com/assets/1225595/3510809/0bdc1eea-06aa-11e4-94a6-cb6dff06eb98.png)
The user can then grab and drag the image's border and the image then immediately resizes the top menu bar at least.  
![screen shot 2014-07-07 at 7 26 09 pm](https://cloud.githubusercontent.com/assets/1225595/3510815/1a275f6e-06aa-11e4-8158-e03a3d315a45.png)
But then the bottom is often below the lower edge of the display, and so the user has to drag the rest of the borders to shrink it enough to see the lower "Show controls" button and panel.

**Comment by dlogan** [comment]
Please lets take a  look at this!  It takes about 10 clicks just to resize the images and find the cell of interest in Classifier.  Images are much bigger than they used to be and so are always too big.

Needs (IMHO)
* Auto-scaling so whole image is displayed 
* Some keyboard shortcuts for navigation (zoom, pan)
* Something to better indicate the cell selected in Classifier, rather than playing "Where's Waldo" trying lo locate a little indicator square.  Maybe a blinking square?  A much bigger indicator? A button/menu item to zoom directly to the object?

**Comment by jhung0** [comment]
What do you think about  having "View full images of selected" show an image with the particular cell in the center. Would that be enough for your 3rd point?

**Comment by jhung0** [comment]
One problem is that if I make the cell the center, you can't really see the whole image even with the scroll bars. I'm not sure if it's better to show the whole image as it is now and having a button that does something like flash an X at the right location or have the image be centered at the cell of interest but only show part of the image.

**Comment by dlogan** [comment]
My UI sense is that it's best to show the whole image, and better indicate the selected object.  Maybe it is enough to simply have a bigger square that always has max intensity?  I believe that the indicator square doe s not always have the max intensity, but gets intensity normalized along with the image at some point, though I have not double-checked this.

**Comment by jhung0** [comment]
Thoughts? ![snip20151212_1](https://cloud.githubusercontent.com/assets/9591682/11764050/a5281096-a0ef-11e5-973f-288f999455e7.png)

**Comment by daviddao** [comment]
I guess autoscaling should solve the location problem! The user can then just increase the contrast like this and the object location is immediately visible:
![screen shot 2015-12-12 at 7 44 11 pm](https://cloud.githubusercontent.com/assets/1241240/11764697/bb795558-a108-11e5-933a-22320308b935.png)

**Comment by daviddao** [comment]
I also opened a new issues for the keyboard shortcuts in general

**Comment by dlogan** [comment]
I like the auto-scaling idea, but color might help to "pop-out" the square too. (Though how do we auto-choose that color?).  
Is it easy to create a checkbox/toggle that would do the auto-scaling like in David D's example, say, near the "Contrast Stretch" radio buttons?  Yes, the slider could just be used, but (a) users might not realize this functionality, and (b) a labeled button is easier to press than using a slider.

**Comment by daviddao** [comment]
@jhung0 since the latest commit ca16a1e , the images are quadratic - which is great for big images but they are also quadratic for low resolution. Following issue: 

<img width="624" alt="screen shot 2015-12-14 at 8 21 16 pm" src="https://cloud.githubusercontent.com/assets/1241240/11799283/aa093600-a2a0-11e5-91ff-e34cb8dee05e.png">

This image could easily fit into my desktop (500 x 600), but due to the squaring i need to scroll down to actually see (and find) the selected object:

<img width="596" alt="screen shot 2015-12-14 at 8 26 47 pm" src="https://cloud.githubusercontent.com/assets/1241240/11799316/08e482e2-a2a1-11e5-9fa8-5a0ed138fed3.png">

We can resolve this by only resizing pictures, when they have a certain min width.

**Comment by jhung0** [comment]
It shouldn't have any effect for smaller images... I'll have to check

**Comment by AnneCarpenter** [comment]
Instead of blinking (!) to point out the cell of interest, I’d vote for a show/hide toggle, to enable the user switching it on and off at will.

**Comment by dlogan** [comment]
Toggling is fine with me, though I would vote for toggling the image, rather than the cursor, as in David D's autos ale example above. If the image is high contrast with large objects,  the box might still be difficult to see. 

And is there a type of toggle that only stays on while you are actively pressing it? That would be nice here, I think, for this sort of temporary view.

**Comment by daviddao** [comment]
I implemented hide and toggle with  ec8e4f5 . Basically, when the user holds CTRL+F (or CMD+F on Mac OS), we can toggle between brightness values 0 and last setting. I also decided to revert #99 because this causes the quadratic resizing of the images mentioned above. This can be annoying for small images and is unnecessary given our new shortcut. 

![screen shot 2015-12-15 at 9 41 36 pm](https://cloud.githubusercontent.com/assets/1241240/11830591/a449f612-a374-11e5-9692-d64cb7cdc10d.png)

**Comment by daviddao** [comment]
You can download and test out the new version for mac [here](https://drive.google.com/a/broadinstitute.com/file/d/0B2aYwrhHkhm4Wm8tdVZQMkd4V3c/view?usp=sharing) (only available for Broadies)

- Selected Objects can now be found by holding CMD+F
- Large images are limited to 1000 px
