### ISSUE TITLE
Follow-up on build for Ubuntu

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler-Analyst#64]
Ok!  Please do, and be sure to provide a link to give him credit. It was Oct 2014 so likely still works.
Anne

On Wed, Jan 14, 2015 at 10:40 AM, Lee Kamentsky <leek@broadinstitute.org> wrote:
It looks like he was successful, but goodness knows when he did this or whether it still works now. I can cut and paste this into a CPA issue. I'd rather not do more than that in the near-term.

On Wed, Jan 14, 2015 at 10:22 AM, Anne Carpenter <anne@broadinstitute.org> wrote:
I stumbled across this from Lee Zamparo who visited us a couple years back. It it useful, and/or has it been incorporated into anything we do or any instructions we've posted?

https://cerevisuals.wordpress.com/2014/10/17/install-cellprofileranalyst-onto-a-debian-ubuntu-workstation/

Anne

**Comment by ljosa** [comment]
Installing CellProfiler from source on Ubuntu is very easy (7 lines, [instructions](http://cellprofiler.org/forum/viewtopic.php?f=14&t=3797#p12106)) because Ubuntu has appropriate versions of almost all the dependencies. CPA uses mostly the same stuff, so I would hope that installing CPA on Ubuntu would be easy as well.

**Comment by AnneCarpenter** [comment]
See also #59 . I think this can be closed.
