### ISSUE TITLE
Allow new CPA classifiers to work with CP's FilterObjects

### ISSUE THREAD

**Issue by jhung0** [CellProfiler/CellProfiler-Analyst#88]
CellProfiler's FilterObjects takes a rules file from the old CPA fast gentle boosting classifier, but this should work with the new CPA classifiers as well

**Comment by daviddao** [comment]
Following Lee's suggestion, we should compress CPA's classifiers using sklearn's joblib and add a version number into the zipped file to keep track of our format and have a quality control. However, we need to edit CP's codebase directly in order to run the trained classifiers. Hence I propose to move this to a feature request on the CP page.

**Comment by jhung0** [comment]
basically works but needs some more methods to make the interface look right (pull request in CP)

**Comment by jhung0** [comment]
closing because it's a CP issue
