### ISSUE TITLE
"Show Controls" display problems

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler-Analyst#93]
When a whole image is shown in Classifier (e.g. double-click on a thumbnail), the "Show Controls" button does not render properly:
![screen shot 2015-12-10 at 1 57 22 pm](https://cloud.githubusercontent.com/assets/1225595/11725181/51359454-9f46-11e5-9bea-b48e1fb382f7.png)
And when you do click the little triangle at the bottom-left, you get this:
![screen shot 2015-12-10 at 1 57 32 pm](https://cloud.githubusercontent.com/assets/1225595/11725194/5deb7d9e-9f46-11e5-803e-945102f0a333.png)

(Running a recent build dmg ~2015/12/02)

**Comment by daviddao** [comment]
## Issue 
Thanks! The reason is that wxPython now has as BaseColor for Mac Panels black. 
I fixed it in the latest issues (with all visualizations) with commit 20ab7f3.

![](http://i.imgur.com/mCUlt53.png)


## New dmg release
Please download the newest secret dmg [newest secret dmg here](https://drive.google.com/a/broadinstitute.com/file/d/0B2aYwrhHkhm4cTRTQnB3cFRmNmM/view?usp=sharing) 
(only for Broadies) 

or 

build it from the "CPA-2.1.0-dev" branch (<b>given you have all dependencies on your machine installed</b>) with following commands:

```
cd CellProfiler-Analyst
git checkout -b "CPA-2.1.0-dev"
python setup.py py2app
```
Setting up jenkins or travis (automatic build) is on my priority list!

**Comment by dlogan** [comment]
Great!  I will try your newest dmg too, thanks.
